### ISSUE TITLE
Ensure new HBP accounts can be quickly approved on the day

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/NeuroinformaticsTutorial#2]

**Comment by apdavison** [comment]
No specific approval is needed. Any HBP member can invite anyone to create an account, so I can do this for all participants.

**Comment by pgleeson** [comment]
Thanks @apdavison. This should probably be mentioned in any of the exercises which require a HBP account (for future users), e.g. https://github.com/NeuralEnsemble/NeuroinformaticsTutorial/blob/master/Exercises/Exercise2_HBP_Collaboratory.md
