### ISSUE TITLE
Add licence info

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/NeuroinformaticsTutorial#3]
Add info on licence. Need to make clear that anyone adding slides uses this licence.

Probably [Creative Commons Attribution Share Alike 4.0](https://choosealicense.com/licenses/cc-by-sa-4.0/) is appropriate?

**Comment by pgleeson** [comment]
@apdavison Thoughts on this? Best settle on it before contacting people re input.

**Comment by apdavison** [comment]
My personal preference would be [CC-BY](https://choosealicense.com/licenses/cc-by-4.0/), but CC-BY-SA is also ok

**Comment by pgleeson** [comment]
Ok, added CC-BY to the README. 
Also added contributors list.
